sonar.projectKey=peterson-lc_psw-digital-frontend-challenge
sonar.organization=peterson-lc

# Source directories
sonar.sources=app,components,lib

# Test directories
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=node_modules/**,coverage/**,.next/**

# Encoding
sonar.sourceEncoding=UTF-8

